image: node:16
pages:
  stage: deploy
  script:
    - rm -R built-web || true
    - npm install --legacy-peer-deps
    - mkdir built-web
    - npm run prettier-check
    - npm run test
    - npm run lint
    - mv coverage built-web # This is broken now for some unknown reasons

    - npm run pack-game-data

    - npm run build

    - > # Pre-compress files for gitlab pages
      find built-web -type f \
        \( \
          -name '*.js' -o -name '*.css' -o -name '*.html' -o -name '*.map' \
          -o -name '*.svg' -o -name '*.json' \
          -o -name '*.woff2' -o -name '*.eot' -o -name '*.ttf' -o -name '*.woff' \
        \) \
        -execdir gzip "{}" --keep --suffix .gz --verbose \;

    - mv built-web public
  artifacts:
    paths:
      - public
  only:
    - master
