image: node:8.11.3
pages:
  stage: deploy
  script:
  - rm -R built-web || true
  - npm install
  - mkdir built-web
  - npm run tsc
  - npm run test
  - mv coverage built-web
  - node built-node/packGameData.js
  - npm run build
  - mv built-web public
  artifacts:
    paths:
    - public
  only:
  - master
